# Generated by Django 6.0.2 on 2026-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preview', models.TextField(max_length=500)),
                ('image', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
